### ISSUE TITLE
Unable to open output file

### ISSUE THREAD

**Issue by jifffffy** [kellyi/nasm-gcc-container#1]
![1541140862 1](https://user-images.githubusercontent.com/5210372/47897583-616c5c00-dead-11e8-9395-3c5d5419ca78.jpg)

**Comment by kellyi** [comment]
Hi! Thanks for reporting this. I haven't tried running the container on Windows, so it might be a little difficult for me to debug quickly.

Assuming `helloworld.asm` is in fact in the dir (you can check this by running `ls` in the running container to see that it's been output), my guess is that the problem might be related to file permissions for the writing the `helloworld.o` file.

On macOS and Linux, the directory's mounted as a volume such that the container can write to the volume and the output file will have the proper permissions:

```
llp@c218d0db8072:/usr/src$ ls -lah
total 16K
drwxr-xr-x 5 llp  llp   160 Nov  2 17:43 .
drwxr-xr-x 1 root root 4.0K Oct 11 00:00 ..
-rw-r--r-- 1 llp  llp   198 Nov  2 17:38 helloworld.asm
-rw-r--r-- 1 llp  llp   864 Nov  2 17:43 helloworld.o
-rwxr-xr-x 1 llp  llp   936 Nov  2 17:43 helloworld.out
```

However, I'm wondering whether Docker on Windows won't work quite the same way?

I'll see if I can find a way to test this out on a Windows machine, but if you'd like to try to fix it definitely feel free to submit a pull request!

**Comment by jifffffy** [comment]
Thank you very much for your quick reply.
The system used for the screenshot is win7. I found 2 problems:
1: I use `ls` can not see helloworld.asm
2: I can't `touch` any file, prompting me not have permission to write.

Now  I use win 10, anything is fine.

**Comment by kellyi** [comment]
Thanks for explaining how to reproduce the error! I'll update the README to indicate that the required operating systems are either Linux, macOS, or Windows 10.
